// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: proto/gophkeeper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Gophkeeper_UserAuth_FullMethodName        = "/gophkeeper.Gophkeeper/UserAuth"
	Gophkeeper_UserLogin_FullMethodName       = "/gophkeeper.Gophkeeper/UserLogin"
	Gophkeeper_UserdataGet_FullMethodName     = "/gophkeeper.Gophkeeper/UserdataGet"
	Gophkeeper_TextdataCreate_FullMethodName  = "/gophkeeper.Gophkeeper/TextdataCreate"
	Gophkeeper_TextdataUpdate_FullMethodName  = "/gophkeeper.Gophkeeper/TextdataUpdate"
	Gophkeeper_TextdataGet_FullMethodName     = "/gophkeeper.Gophkeeper/TextdataGet"
	Gophkeeper_CredsdataCreate_FullMethodName = "/gophkeeper.Gophkeeper/CredsdataCreate"
)

// GophkeeperClient is the client API for Gophkeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GophkeeperClient interface {
	UserAuth(ctx context.Context, in *UserAuthRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UserdataGet(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserdataGetResponse, error)
	TextdataCreate(ctx context.Context, in *TextDataStoreRequest, opts ...grpc.CallOption) (*CallbackStatusResponse, error)
	TextdataUpdate(ctx context.Context, in *TextDataUpdateRequest, opts ...grpc.CallOption) (*CallbackStatusResponse, error)
	TextdataGet(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TextdataEntriesResponse, error)
	CredsdataCreate(ctx context.Context, in *CredsdataStoreRequest, opts ...grpc.CallOption) (*CallbackStatusResponse, error)
}

type gophkeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewGophkeeperClient(cc grpc.ClientConnInterface) GophkeeperClient {
	return &gophkeeperClient{cc}
}

func (c *gophkeeperClient) UserAuth(ctx context.Context, in *UserAuthRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Gophkeeper_UserAuth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Gophkeeper_UserLogin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) UserdataGet(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserdataGetResponse, error) {
	out := new(UserdataGetResponse)
	err := c.cc.Invoke(ctx, Gophkeeper_UserdataGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) TextdataCreate(ctx context.Context, in *TextDataStoreRequest, opts ...grpc.CallOption) (*CallbackStatusResponse, error) {
	out := new(CallbackStatusResponse)
	err := c.cc.Invoke(ctx, Gophkeeper_TextdataCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) TextdataUpdate(ctx context.Context, in *TextDataUpdateRequest, opts ...grpc.CallOption) (*CallbackStatusResponse, error) {
	out := new(CallbackStatusResponse)
	err := c.cc.Invoke(ctx, Gophkeeper_TextdataUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) TextdataGet(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TextdataEntriesResponse, error) {
	out := new(TextdataEntriesResponse)
	err := c.cc.Invoke(ctx, Gophkeeper_TextdataGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) CredsdataCreate(ctx context.Context, in *CredsdataStoreRequest, opts ...grpc.CallOption) (*CallbackStatusResponse, error) {
	out := new(CallbackStatusResponse)
	err := c.cc.Invoke(ctx, Gophkeeper_CredsdataCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GophkeeperServer is the server API for Gophkeeper service.
// All implementations must embed UnimplementedGophkeeperServer
// for forward compatibility
type GophkeeperServer interface {
	UserAuth(context.Context, *UserAuthRequest) (*emptypb.Empty, error)
	UserLogin(context.Context, *UserLoginRequest) (*emptypb.Empty, error)
	UserdataGet(context.Context, *emptypb.Empty) (*UserdataGetResponse, error)
	TextdataCreate(context.Context, *TextDataStoreRequest) (*CallbackStatusResponse, error)
	TextdataUpdate(context.Context, *TextDataUpdateRequest) (*CallbackStatusResponse, error)
	TextdataGet(context.Context, *emptypb.Empty) (*TextdataEntriesResponse, error)
	CredsdataCreate(context.Context, *CredsdataStoreRequest) (*CallbackStatusResponse, error)
	mustEmbedUnimplementedGophkeeperServer()
}

// UnimplementedGophkeeperServer must be embedded to have forward compatible implementations.
type UnimplementedGophkeeperServer struct {
}

func (UnimplementedGophkeeperServer) UserAuth(context.Context, *UserAuthRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserAuth not implemented")
}
func (UnimplementedGophkeeperServer) UserLogin(context.Context, *UserLoginRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}
func (UnimplementedGophkeeperServer) UserdataGet(context.Context, *emptypb.Empty) (*UserdataGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserdataGet not implemented")
}
func (UnimplementedGophkeeperServer) TextdataCreate(context.Context, *TextDataStoreRequest) (*CallbackStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TextdataCreate not implemented")
}
func (UnimplementedGophkeeperServer) TextdataUpdate(context.Context, *TextDataUpdateRequest) (*CallbackStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TextdataUpdate not implemented")
}
func (UnimplementedGophkeeperServer) TextdataGet(context.Context, *emptypb.Empty) (*TextdataEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TextdataGet not implemented")
}
func (UnimplementedGophkeeperServer) CredsdataCreate(context.Context, *CredsdataStoreRequest) (*CallbackStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CredsdataCreate not implemented")
}
func (UnimplementedGophkeeperServer) mustEmbedUnimplementedGophkeeperServer() {}

// UnsafeGophkeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GophkeeperServer will
// result in compilation errors.
type UnsafeGophkeeperServer interface {
	mustEmbedUnimplementedGophkeeperServer()
}

func RegisterGophkeeperServer(s grpc.ServiceRegistrar, srv GophkeeperServer) {
	s.RegisterService(&Gophkeeper_ServiceDesc, srv)
}

func _Gophkeeper_UserAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).UserAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_UserAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).UserAuth(ctx, req.(*UserAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_UserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).UserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_UserLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).UserLogin(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_UserdataGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).UserdataGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_UserdataGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).UserdataGet(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_TextdataCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextDataStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).TextdataCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_TextdataCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).TextdataCreate(ctx, req.(*TextDataStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_TextdataUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextDataUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).TextdataUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_TextdataUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).TextdataUpdate(ctx, req.(*TextDataUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_TextdataGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).TextdataGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_TextdataGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).TextdataGet(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_CredsdataCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredsdataStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).CredsdataCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_CredsdataCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).CredsdataCreate(ctx, req.(*CredsdataStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gophkeeper_ServiceDesc is the grpc.ServiceDesc for Gophkeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gophkeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophkeeper.Gophkeeper",
	HandlerType: (*GophkeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserAuth",
			Handler:    _Gophkeeper_UserAuth_Handler,
		},
		{
			MethodName: "UserLogin",
			Handler:    _Gophkeeper_UserLogin_Handler,
		},
		{
			MethodName: "UserdataGet",
			Handler:    _Gophkeeper_UserdataGet_Handler,
		},
		{
			MethodName: "TextdataCreate",
			Handler:    _Gophkeeper_TextdataCreate_Handler,
		},
		{
			MethodName: "TextdataUpdate",
			Handler:    _Gophkeeper_TextdataUpdate_Handler,
		},
		{
			MethodName: "TextdataGet",
			Handler:    _Gophkeeper_TextdataGet_Handler,
		},
		{
			MethodName: "CredsdataCreate",
			Handler:    _Gophkeeper_CredsdataCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gophkeeper.proto",
}
